### ISSUE TITLE
compound model

### ISSUE THREAD

**Issue by kdionisio** [Chemical-Curation/chemcurator_ws#1]
As a product owner
I would like to store a compound
So that I can use it in my application

This is an abstract class

Compound consists of:
- ID = DTXCID002000000 (auto increment from 2,000,000 up) (required field)
- Definitive structure string - Text Field (required field)

Acceptance Criteria:
A test to show when a compound is created it has the appropriate ID and Definitive structure

**Comment by dmlyons2** [comment]
Issue moved to [Chemical-Curation/chemcurator #2](https://github.com/Chemical-Curation/chemcurator/issues/2) via [**ZenHub**](https://www.zenhub.com/)
